language: android
jdk:
  - oraclejdk8
android:
    components:
      - platform-tools
      - tools
      - build-tools-24.0.1
      - android-24
      - extra-android-m2repository
      
script:
    - ./gradlew clean assembleDebug --info
    - ./gradlew build jacocoTestReport
    
after_success:
    - bash <(curl -s https://codecov.io/bash)
